name: Train YOLOv8 Model

on: push

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training
      run: python employee-monitoring/train.py --img 640 --batch 16 --epochs 50 --data coco.yaml --weights yolov8n.pt
