name: Train YOLOv8 Model

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # 每周日运行

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install ultralytics opencv-python-headless

      - name: Train YOLOv8 model
        run: |
          python -c "
          from ultralytics import YOLO;
          model = YOLO('yolov8n.pt');
          model.train(data='path/to/dataset.yaml', epochs=50, imgsz=640);
          "
