name: Train YOLOv8 Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r employee-monitoring/requirements.txt

    - name: List directory contents for debugging
      run: ls -R employee-monitoring/src

    - name: Run training
      run: |
        python employee-monitoring/src/train.py --img 640 --batch 16 --epochs 50 --data coco.yaml --weights yolov8n.pt
